---
language: vim
dist: focal

before_script:
  - export REPO_DIR=$(pwd)
  - git clone https://github.com/junegunn/vader.vim.git test/vader.vim
  - |
    echo 'Clone vim repo.'
    cd ~/
    sudo apt-get remove vim -y
    git clone https://github.com/vim/vim
    cd vim
  - |
    echo 'Build and install vim 8.1.0039.'
    make distclean
    git checkout v8.1.0039
    ./configure --with-features=huge --prefix=$HOME/out/8
    make -j install
  - sudo add-apt-repository ppa:neovim-ppa/stable -y
  - sudo apt-get update  -q
  - sudo apt-get install -y language-pack-de
  - |
    sudo apt-get install -y neovim
    nvim --version

script:
  - cd "$REPO_DIR/test"  # to make handling filepaths easier
  - ./run_tests.sh --international --neovim
  - ./run_tests.sh --international --vim_exe=$HOME/out/8/bin/vim
