---
language: vim

before_script:
  - sudo add-apt-repository ppa:jonathonf/vim -y
  - |
    if [[ `lsb_release -r | awk '{print $2}'` < 16.04 ]]; then
      echo "Using neovim-ppa/unstable for Ubuntu version older than 16.04."
      sudo add-apt-repository ppa:neovim-ppa/unstable -y
    else
      echo "Using neovim-ppa/stable for Ubuntu version 16.04 or newer."
      sudo add-apt-repository ppa:neovim-ppa/stable   -y
    fi
  - sudo apt-get update  -q
  - sudo apt-get install -y language-pack-de language-pack-es
  - |
    sudo apt-get remove vim -y
    sudo apt-get install -y vim
    vim  --version
  - |
    sudo apt-get install -y neovim vim
    nvim --version
  - git clone https://github.com/junegunn/vader.vim.git test/vader.vim

script:
  - cd test  # to make handling filepaths easier
  - ./run_tests.sh --international --neovim
  - ./run_tests.sh --international
